packageExtensions:
  webpack@*:
    dependencies:
      lodash: ^4.15.0
    peerDependencies:
      webpack-cli: "*"
    peerDependenciesMeta:
      webpack-cli:
        optional: true

yarnPath: .yarn/releases/yarn-3.1.0-rc.11.cjs
